// Copyright 2026 Spotted Loaf Studio

#pragma once

#include "HAL/PlatformMisc.h"
#include "Stats/Stats.h"

/** Cycle stats and compact counters for layout-generation profiling in Unreal Insights and `stat PorismLayout`. */
DECLARE_STATS_GROUP(TEXT("Porism Layout"), STATGROUP_PorismLayout, STATCAT_Advanced);

DECLARE_CYCLE_STAT_EXTERN(TEXT("Candidate Discovery"), STAT_PorismLayout_Discovery, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Prewarm Total"), STAT_PorismLayout_Prewarm, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Prewarm Mode Plan"), STAT_PorismLayout_PrewarmModePlan, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Adapter Precompute"), STAT_PorismLayout_AdapterPrecompute, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Contract Adapter"), STAT_PorismLayout_ContractAdapter, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Stepped Plan Finalize"), STAT_PorismLayout_SteppedPlanFinalize, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Standard Contract Apply"), STAT_PorismLayout_StandardContractApply, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Root Worker Total"), STAT_PorismLayout_RootWorker, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Request Finalize"), STAT_PorismLayout_RequestFinalize, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Region Tree Solve"), STAT_PorismLayout_RegionTreeSolve, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Leaf Region Solve"), STAT_PorismLayout_LeafSolve, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Live Context Build"), STAT_PorismLayout_ContextBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Plan Build"), STAT_PorismLayout_PlanBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Variant Build"), STAT_PorismLayout_VariantBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Initial Domains"), STAT_PorismLayout_InitialDomains, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Route Preparation"), STAT_PorismLayout_RoutePreparation, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Route Domain Stage"), STAT_PorismLayout_RouteDomain, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Search Prefix"), STAT_PorismLayout_SearchPrefix, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Branch Search"), STAT_PorismLayout_BranchSearch, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Branch Continuation"), STAT_PorismLayout_BranchContinuation, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Search Frontier"), STAT_PorismLayout_SearchFrontier, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forced Placements"), STAT_PorismLayout_ForcedPlacements, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forced Bundle Placements"), STAT_PorismLayout_ForcedBundlePlacements, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forced Singleton Resolution"), STAT_PorismLayout_ForcedSingletonResolution, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forced Placement Reachability"), STAT_PorismLayout_ForcedPlacementReachability, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forced Candidate Scan"), STAT_PorismLayout_ForcedCandidateScan, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("MRV Selection"), STAT_PorismLayout_MRVSelection, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Exact Branch Reduction"), STAT_PorismLayout_ExactBranchReduction, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Branch Apply"), STAT_PorismLayout_BranchApply, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Candidate Bundle Commit"), STAT_PorismLayout_CandidateBundleCommit, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Forward Check"), STAT_PorismLayout_ForwardCheck, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Best Partial Capture"), STAT_PorismLayout_BestPartialCapture, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Leaf Result Finalize"), STAT_PorismLayout_LeafResultFinalize, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Compatibility Index"), STAT_PorismLayout_CompatibilityIndex, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Propagation"), STAT_PorismLayout_Propagation, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Search"), STAT_PorismLayout_Search, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Reachability"), STAT_PorismLayout_Reachability, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Closure Evaluation"), STAT_PorismLayout_Closure, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Recursive Negotiation"), STAT_PorismLayout_RecursiveNegotiation, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Candidate Normalization"), STAT_PorismLayout_CandidateNormalization, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Memo Key Build"), STAT_PorismLayout_MemoKeyBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Probe Total"), STAT_PorismLayout_ProbeTotal, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Parent Probe"), STAT_PorismLayout_ParentProbe, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Deferred Validation"), STAT_PorismLayout_DeferredValidation, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Child Proof"), STAT_PorismLayout_ChildProof, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Merge And Audit"), STAT_PorismLayout_MergeAudit, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Post Structural"), STAT_PorismLayout_PostStructural, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Solved Artifact"), STAT_PorismLayout_SolvedArtifact, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Realization Prep"), STAT_PorismLayout_RealizationPrep, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Realization Apply"), STAT_PorismLayout_RealizationApply, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Realization Total"), STAT_PorismLayout_Realization, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Realization Asset Rehydrate"), STAT_PorismLayout_RealizationAssetRehydrate, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Replay"), STAT_PorismLayout_TerrainReplay, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Template Placement"), STAT_PorismLayout_TemplatePlacement, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Selected Site Terrain Total"), STAT_PorismLayout_SelectedSiteTerrainTotal, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Position Build"), STAT_PorismLayout_TerrainPositionBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Material Read"), STAT_PorismLayout_TerrainMaterialRead, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Component Build"), STAT_PorismLayout_TerrainComponentBuild, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Biome Owner Read"), STAT_PorismLayout_TerrainBiomeOwnerRead, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_CYCLE_STAT_EXTERN(TEXT("Terrain Fit Evidence"), STAT_PorismLayout_TerrainFitEvidence, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);

DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Region Solve Calls"), STAT_PorismLayout_RegionSolveCalls, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Parent Probe Calls"), STAT_PorismLayout_ParentProbeCalls, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Parent Full Proof Calls"), STAT_PorismLayout_ParentFullProofCalls, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Deferred Validation Calls"), STAT_PorismLayout_DeferredValidationCalls, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Child Proof Calls"), STAT_PorismLayout_ChildProofCalls, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Search States"), STAT_PorismLayout_SearchStates, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Propagation Runs"), STAT_PorismLayout_PropagationRuns, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Propagation Passes"), STAT_PorismLayout_PropagationPasses, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Candidate Attempts"), STAT_PorismLayout_CandidateAttempts, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Backtracks"), STAT_PorismLayout_Backtracks, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Arc Queue Pops"), STAT_PorismLayout_ArcQueuePops, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Support Checks"), STAT_PorismLayout_SupportChecks, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Candidate Removals"), STAT_PorismLayout_CandidateRemovals, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Failed Cells"), STAT_PorismLayout_FailedCells, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Stages"), STAT_PorismLayout_TerrainStages, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Blocked Frontiers"), STAT_PorismLayout_TerrainBlockedFrontiers, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Backtracks"), STAT_PorismLayout_TerrainBacktracks, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Material Positions"), STAT_PorismLayout_TerrainMaterialPositions, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Biome Positions"), STAT_PorismLayout_TerrainBiomePositions, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Packet Bytes"), STAT_PorismLayout_TerrainPacketBytes, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Selected Columns"), STAT_PorismLayout_TerrainSelectedColumns, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Foundation Write Positions"), STAT_PorismLayout_TerrainFoundationWritePositions, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Entry Halo Write Positions"), STAT_PorismLayout_TerrainEntryHaloWritePositions, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);
DECLARE_DWORD_ACCUMULATOR_STAT_EXTERN(TEXT("Terrain Template Footprint Excavation Positions"), STAT_PorismLayout_TerrainTemplateExcavationWritePositions, STATGROUP_PorismLayout, PORISMDIMSWORLDGENERATOREXTENSION_API);

/** Adds UE named event plus matching aggregate cycle stat without formatting dynamic strings. */
#define PORISM_LAYOUT_PROFILE_SCOPE(EventName, StatName) \
	SCOPED_NAMED_EVENT(EventName, FColor::Cyan); \
	SCOPE_CYCLE_COUNTER(StatName)

/** Adds named speculative-work event plus specific and aggregate probe cycle stats. */
#define PORISM_LAYOUT_PROBE_SCOPE(EventName, StatName) \
	SCOPED_NAMED_EVENT(EventName, FColor::Orange); \
	SCOPE_CYCLE_COUNTER(StatName); \
	SCOPE_CYCLE_COUNTER(STAT_PorismLayout_ProbeTotal)
