// Copyright 2026 Spotted Loaf Studio

#pragma once

#include "CoreMinimal.h"
#include "ChunkWorld/Spawn/ChunkWorldSpawnTypes.h"
#include "Components/ActorComponent.h"
#include "GameFramework/CharacterMovementComponent.h"
#include "ChunkWorldReadinessFreezeComponent.generated.h"

class AChunkWorldExtended;
class AController;
class UChunkWorldLayoutRuntimeComponent;
class UMovementComponent;
class UPrimitiveComponent;

DECLARE_DYNAMIC_MULTICAST_DELEGATE(FPorismStartupFreezeSignature);
DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnChunkWorldRuntimeClientReady, FGuid, SessionId, FGuid, ReadinessId);

/** Identifies lifecycle state for one replicated runtime readiness session. */
UENUM(BlueprintType)
enum class EChunkWorldRuntimeReadinessState : uint8
{
	Inactive UMETA(DisplayName = "Inactive"),
	WaitingForWalker UMETA(DisplayName = "Waiting For Walker"),
	WaitingForServerReady UMETA(DisplayName = "Waiting For Server Ready"),
	WaitingForClientReady UMETA(DisplayName = "Waiting For Client Ready"),
	Settled UMETA(DisplayName = "Settled"),
	Failed UMETA(DisplayName = "Failed"),
	Canceled UMETA(DisplayName = "Canceled"),
	WaitingForLayouts UMETA(DisplayName = "Waiting For Layouts")
};

/** Explains why runtime readiness retained its freeze instead of releasing its owner. */
UENUM(BlueprintType)
enum class EChunkWorldRuntimeReadinessFailure : uint8
{
	None UMETA(DisplayName = "None"),
	InvalidRequest UMETA(DisplayName = "Invalid Request"),
	WalkerUnavailable UMETA(DisplayName = "Walker Unavailable"),
	ClientAcknowledgementTimeout UMETA(DisplayName = "Client Acknowledgement Timeout"),
	InvalidClientAcknowledgement UMETA(DisplayName = "Invalid Client Acknowledgement"),
	InvalidTraceProfile UMETA(DisplayName = "Invalid Trace Profile"),
	NoSettledSurface UMETA(DisplayName = "No Settled Surface"),
	WorldTornDown UMETA(DisplayName = "World Torn Down"),
	OwnerTornDown UMETA(DisplayName = "Owner Torn Down"),
	LayoutWaitTimeout UMETA(DisplayName = "Layout Wait Timeout")
};

/** Replicated server-authoritative state for one character-owned runtime settlement session. */
USTRUCT(BlueprintType)
struct PORISMDIMSWORLDGENERATOREXTENSION_API FChunkWorldRuntimeReadinessSession
{
	GENERATED_BODY()

	/** Opaque session id generated by authority and required by the owning-client acknowledgement. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Opaque session id generated by authority and required by the owning-client acknowledgement."))
	FGuid SessionId;

	/** Receipt identity rearmed after nearby layout work; operation SessionId stays stable for gameplay. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Current native-readiness receipt identity. Owning-client acknowledgements must match it as well as the operation session; old receipts cannot release changed terrain."))
	FGuid ReadinessId;

	/** Chunk world that receives local walker-ready observations for this session. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Chunk world that receives local walker-ready observations for this session."))
	TObjectPtr<AChunkWorldExtended> ChunkWorld = nullptr;

	/** Exact registered owner walker selected by authority for this session. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Exact registered owner walker selected by authority for this session. Other owner walkers cannot satisfy it."))
	TObjectPtr<UObject> TrackedWalker = nullptr;

	/** Bounded source region inherited from the approved location result. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Bounded source region inherited from the approved location result. Settlement never searches outside it."))
	FChunkWorldSpawnRegion CandidateRegion;

	/** True when authority must receive one acknowledgement from the owning client before settlement. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "True when authority must receive one acknowledgement from the owning client before settlement."))
	bool bRequiresOwningClientReady = false;

	/** True after authority receives its tracked walker's finest-detail event. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "True after authority receives its tracked walker's finest-detail event."))
	bool bServerWalkerReady = false;

	/** True after authority validates and accepts one owning-client acknowledgement. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "True after authority validates and accepts one owning-client acknowledgement."))
	bool bOwningClientReady = false;

	/** Authoritative lifecycle state. Terminal failure intentionally retains actor freeze. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Authoritative lifecycle state. Terminal failure intentionally retains actor freeze."))
	EChunkWorldRuntimeReadinessState State = EChunkWorldRuntimeReadinessState::Inactive;

	/** Structured terminal failure reason when state is Failed or Canceled. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Structured terminal failure reason when state is Failed or Canceled."))
	EChunkWorldRuntimeReadinessFailure Failure = EChunkWorldRuntimeReadinessFailure::None;

	/** Server-selected final transform replicated to every client before release. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Server-selected final transform replicated to every client before release."))
	FTransform SettledTransform = FTransform::Identity;

	/** Compact diagnostic text for gameplay logging and failure handling. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Compact diagnostic text for gameplay logging and failure handling."))
	FString DebugReason;
};

DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOnChunkWorldRuntimeReadinessResult, const FChunkWorldRuntimeReadinessSession&, Session);

/** Holds an actor frozen for startup and server-authoritative runtime terrain settlement. */
UCLASS(ClassGroup = (Porism), BlueprintType, meta = (BlueprintSpawnableComponent, DisplayName = "Chunk World Readiness Freeze Component"))
class PORISMDIMSWORLDGENERATOREXTENSION_API UChunkWorldReadinessFreezeComponent : public UActorComponent
{
	GENERATED_BODY()

public:
	/** Creates a readiness-freeze component with startup freeze enabled by default. */
	UChunkWorldReadinessFreezeComponent();

	/** Returns true while this component is still holding the owner in its startup-frozen state. */
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "ChunkWorld|Startup")
	bool IsStartupFreezeActive() const { return bStartupFreezeActive; }

	/** Combined safety gate for gameplay/loading consumers; terminal failures remain frozen. */
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "ChunkWorld|Readiness")
	bool IsReadinessFreezeActive() const { return bStartupFreezeActive || bRuntimeFreezeActive || IsRuntimeFreezeActive(); }

	/** Returns true once this component has discovered at least one relevant chunk world for the owner's walkers. */
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "ChunkWorld|Startup")
	bool HasResolvedStartupChunkWorlds() const { return bHasResolvedStartupChunkWorlds; }

	/** Returns current replicated runtime settlement session state. */
	UFUNCTION(BlueprintCallable, BlueprintPure, Category = "ChunkWorld|Runtime Readiness")
	FChunkWorldRuntimeReadinessSession GetRuntimeReadinessSession() const { return RuntimeSession; }

	/** Allows a late-bound owning controller to reconcile the current local-ready notification. */
	bool IsLocalRuntimeReadyForAcknowledgement() const
	{
		return bLocalClientReadyBroadcast && RuntimeTrackedReadinessId == RuntimeSession.ReadinessId
			&& RuntimeSession.SessionId.IsValid() && !IsRuntimeSessionTerminal();
	}

	/** Starts authority-owned settlement, superseding an automatic startup session but never another explicit request.
	 * Returns the stable operation id, or an invalid id on rejection. */
	UFUNCTION(BlueprintCallable, Category = "ChunkWorld|Runtime Readiness")
	FGuid StartRuntimeReadinessSession(AChunkWorldExtended* ChunkWorld, const FChunkWorldSpawnRegion& CandidateRegion, bool bRequireOwningClientReady);

	/** Cancels matching authority session. Cancellation retains freeze until game teardown or a later explicit session. */
	UFUNCTION(BlueprintCallable, Category = "ChunkWorld|Runtime Readiness")
	bool CancelRuntimeReadinessSession(FGuid SessionId);

	/** Validates and records one owning-client acknowledgement on authority. Duplicate acknowledgements are idempotent. */
	bool AcknowledgeOwningClientRuntimeReady(AController* Controller, FGuid SessionId, FGuid ReadinessId);

	/** Applies startup freeze immediately when the owner has at least one chunk walker. */
	UFUNCTION(BlueprintCallable, Category = "ChunkWorld|Startup")
	void ApplyStartupFreeze();

	/** Releases startup freeze and restores captured state only when no runtime session still requires freeze. */
	UFUNCTION(BlueprintCallable, Category = "ChunkWorld|Startup")
	void ReleaseStartupFreeze();

	/** Broadcast after startup freeze has been applied to the owner. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Startup")
	FPorismStartupFreezeSignature OnStartupFreezeApplied;

	/** Broadcast after startup freeze has been released from the owner. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Startup")
	FPorismStartupFreezeSignature OnStartupFreezeReleased;

	/** Owning-client signal for game controller code to send its reliable session-id acknowledgement. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Runtime Readiness")
	FOnChunkWorldRuntimeClientReady OnOwningClientRuntimeReady;

	/** Broadcast once per operation on each role after runtime freeze is active, including already-running owners. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Runtime Readiness")
	FOnChunkWorldRuntimeReadinessResult OnRuntimeReadinessStarted;

	/** Broadcast on every role when replicated runtime settlement succeeds. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Runtime Readiness")
	FOnChunkWorldRuntimeReadinessResult OnRuntimeReadinessSettled;

	/** Broadcast on every role when runtime settlement fails or is canceled while freeze remains active. */
	UPROPERTY(BlueprintAssignable, Category = "ChunkWorld|Runtime Readiness")
	FOnChunkWorldRuntimeReadinessResult OnRuntimeReadinessFailed;

protected:
	virtual void BeginPlay() override;
	virtual void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
	virtual void TickComponent(float DeltaTime, enum ELevelTick TickType, FActorComponentTickFunction* ThisTickFunction) override;
	virtual void GetLifetimeReplicatedProps(TArray<FLifetimeProperty>& OutLifetimeProps) const override;

	/** If true, startup freeze is applied automatically during BeginPlay when the owner exposes at least one chunk walker. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Startup", meta = (ToolTip = "If true, startup freeze is applied automatically during BeginPlay when the owner exposes at least one chunk walker."))
	bool bAutoApplyOnBeginPlay = true;

	/** If true, owner transform is pinned while startup or runtime freeze is active. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Startup", meta = (ToolTip = "If true, owner transform is pinned while startup or runtime freeze is active so custom movement code cannot drift before readiness."))
	bool bPinActorTransformWhileFrozen = true;

	/** Delay before component warns that none of owner's startup walkers registered with a chunk world yet. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Startup", meta = (ClampMin = "0.0", UIMin = "0.0", ToolTip = "Delay before component warns that none of owner's startup walkers registered with a chunk world yet."))
	float MissingRegistrationWarningDelaySeconds = 2.0f;

	/** Collision profile used for one bounded capsule sweep during runtime settlement. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Collision profile used for one bounded capsule sweep during runtime settlement."))
	FName RuntimeSettlementCollisionProfile = TEXT("BlockAll");

	/** Vertical offset applied above settled terrain contact before actor transform is committed. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ToolTip = "Vertical offset applied above settled terrain contact before actor transform is committed."))
	float RuntimeSettlementZOffset = 0.0f;

	/** Maximum distance above provisional location inspected by runtime settlement sweep. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ClampMin = "0.0", UIMin = "0.0", ToolTip = "Maximum distance above provisional location inspected by runtime settlement sweep."))
	float RuntimeSettlementUpwardScanDistance = 1000.0f;

	/** Maximum distance below provisional location inspected by runtime settlement sweep. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ClampMin = "0.0", UIMin = "0.0", ToolTip = "Maximum distance below provisional location inspected by runtime settlement sweep."))
	float RuntimeSettlementDownwardScanDistance = 2000.0f;

	/** Maximum authority wait for required owning-client finest-detail acknowledgement. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ClampMin = "0.0", UIMin = "0.0", ToolTip = "Maximum authority wait for required owning-client finest-detail acknowledgement. Zero fails immediately when acknowledgement is required."))
	float RuntimeClientReadyTimeoutSeconds = 20.0f;

	/** Bounds local layout waits without releasing into unfinished writes on failure. */
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "ChunkWorld|Runtime Readiness", meta = (ClampMin = "0.0", UIMin = "0.0", ToolTip = "Maximum elapsed time from the first nearby layout wait in a spawn session. Expiry fails and retains freeze. Does not consume or extend the separate client-acknowledgement timeout."))
	float RuntimeLayoutWaitTimeoutSeconds = 60.0f;

private:
	struct FObservedChunkWorldState
	{
		TWeakObjectPtr<AChunkWorldExtended> ChunkWorld;
		bool bReady = false;
	};

	struct FMovementFreezeState
	{
		TWeakObjectPtr<UMovementComponent> MovementComponent;
		bool bWasActive = false;
		bool bTickEnabled = false;
		bool bIsCharacterMovement = false;
		EMovementMode CharacterMovementMode = MOVE_None;
		uint8 CustomMovementMode = 0;
		float GravityScale = 1.0f;
	};

	struct FPrimitiveFreezeState
	{
		TWeakObjectPtr<UPrimitiveComponent> PrimitiveComponent;
		bool bWasSimulatingPhysics = false;
		bool bHadGravityEnabled = false;
		FVector LinearVelocity = FVector::ZeroVector;
		FVector AngularVelocityDegrees = FVector::ZeroVector;
	};

	void RefreshOwnerWalkers();
	void CacheAndApplyFreezeState();
	void RestoreFrozenState();
	void MaintainFrozenTransform() const;
	void RefreshObservedChunkWorlds();
	/** Startup uses the authoritative runtime handshake; clients also retain their local native prerequisite. */
	void TryFinishStartupFreeze();
	bool AreObservedChunkWorldsReady() const;
	void UpdateObservedChunkWorldState(AChunkWorldExtended* ChunkWorld);

	/** Starts local per-walker tracking for replicated runtime session without global actor discovery. */
	void StartLocalRuntimeWalkerTracking();
	void StopLocalRuntimeWalkerTracking();
	void TrySettleRuntimeSession();
	/** Discards server/client native receipts without changing gameplay's operation identity. */
	void RearmRuntimeReadiness();
	/** Subscribe only while a spawn session can still release; never refreeze settled actors. */
	void ObserveLayoutWrites(AChunkWorldExtended* ChunkWorld);
	void StopObservingLayoutWrites();
	void HandleAutomaticLayoutWrite(AChunkWorldExtended* ChunkWorld, const FBox& WorldBounds);
	bool TryBuildRuntimeSettledTransform(FTransform& OutTransform, EChunkWorldRuntimeReadinessFailure& OutFailure, FString& OutFailureReason) const;
	bool HasBoundRuntimeWalker() const;
	void SetRuntimeTerminal(EChunkWorldRuntimeReadinessState TerminalState, EChunkWorldRuntimeReadinessFailure Failure, const FString& DebugReason, const FTransform* SettledTransform = nullptr);
	void RefreshFreezeTick();
	bool IsRuntimeFreezeActive() const;
	bool IsRuntimeSessionTerminal() const;
	void NotifyRuntimeStartedOnce();
	void NotifyRuntimeTerminalOnce();

	/** Receives startup-ready signals for observed startup chunk worlds. */
	UFUNCTION()
	void HandleObservedChunkWorldReady(AChunkWorldExtended* ChunkWorld);

	/** Receives the tracking receipt id registered with the chunk world, not the gameplay operation id. */
	UFUNCTION()
	void HandleRuntimeWalkerReady(AChunkWorldExtended* ChunkWorld, UObject* Walker, FGuid ReadinessId);

	/** Rebuilds local freeze/tracking state after authority session state replicates. */
	UFUNCTION()
	void OnRep_RuntimeSession();

	FTransform FrozenActorTransform = FTransform::Identity;
	TArray<FMovementFreezeState> FrozenMovementStates;
	TArray<FPrimitiveFreezeState> FrozenPrimitiveStates;
	TArray<TWeakObjectPtr<UObject>> OwnerWalkers;
	TArray<FObservedChunkWorldState> ObservedChunkWorldStates;
	TArray<TWeakObjectPtr<UChunkWorldLayoutRuntimeComponent>> ObservedLayoutWriters;
	/** Exact owner walker registered for current runtime session. */
	TWeakObjectPtr<UObject> RuntimeTrackedWalker;
	TWeakObjectPtr<AChunkWorldExtended> RuntimeTrackedChunkWorld;
	FGuid RuntimeTrackedReadinessId;
	float StartupFreezeElapsedSeconds = 0.0f;
	double RuntimeSessionStartTimeSeconds = 0.0;
	double RuntimeLayoutWaitStartTimeSeconds = -1.0;
	FGuid LastRuntimeStartedNotificationId;
	FGuid LastRuntimeTerminalNotificationId;
	bool bStartupFreezeActive = false;
	bool bRuntimeFreezeActive = false;
	/** An explicit approved spawn region may replace only the component's automatic startup request. */
	bool bAutomaticStartupSession = false;
	/** Cancellation callbacks cannot replace an operation while its explicit handoff is being installed. */
	bool bStartingRuntimeSession = false;
	bool bFreezeStateCaptured = false;
	bool bHasResolvedStartupChunkWorlds = false;
	bool bLoggedMissingRegistrationWarning = false;
	bool bLocalClientReadyBroadcast = false;

	/** Server-authoritative session state. Owner component replication distributes final transform and release state. */
	UPROPERTY(ReplicatedUsing = OnRep_RuntimeSession)
	FChunkWorldRuntimeReadinessSession RuntimeSession;
};
